[package]
name = "hello"
version = "0.1.0"
edition = "2021"
authors = ["Daohan Chong <wildcat.name@gmail.com>"]

[lib]
name = "hello"
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = "0.18.0"
uniffi_macros = "0.18.0"
anchor-client = { path = "../../anchor/client/", features = ["debug"] }

[build-dependencies]
uniffi_build = "0.18.0"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort'     # Abort on panic
debug = true # Enable debug symbols. For example, we can use `dwarfdump` to check crash traces.
